### ISSUE TITLE
Problem using https

### ISSUE THREAD

**Issue by sebastian-luna-valero** [stackhpc/monasca-agent-chart#1]
Hi,

I am trying to use `monasca-agent-chart` on a kubernetes cluster deployed with Magnum on OpenStack train.

In the `override.yaml` file I have:
```
url: https://openstack-control-plane:5000/v3
monasca_url: http://openstack-control-plane:8070/v2.0
monasca_log_url: http://openstack-control-plane:5607

```

When I run `kubectl logs pod/monasca-agent-55c4cd49b5-9rvfd -c monasca-agent-forwarder-deployment` I get:
```
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.rea
dthedocs.io/en/latest/advanced-usage.html#ssl-warnings                                                      
  InsecureRequestWarning)                     
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.rea
dthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)                                                                              
2021-02-10 09:20:16,541 | ERROR | forwarder | tornado.application(ioloop.py:638) | Exception in callback <bound method Forwarder.flush of <monasca_agent.forwarder.daemon.Forwarder object at 0x7f9f5006c828>>
Traceback (most recent call last):                                                                                                                                                                                
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 1026, in _run                                                                                                                              
    return self.callback()                                                                                                                                                                                        
  File "/usr/local/lib/python3.6/site-packages/monasca_agent/forwarder/daemon.py", line 168, in flush
    self._post_metrics()                                                                                                                                                                                           
  File "/usr/local/lib/python3.6/site-packages/monasca_agent/forwarder/daemon.py", line 159, in _post_metrics
    self._endpoint.post_metrics(message_batch)                                                
  File "/usr/local/lib/python3.6/site-packages/monasca_agent/forwarder/api/monasca_api.py", line 136, in post_metrics                                                                                         
    self._post(tenant_group[tenant], tenant)                                                                                                                                                                      
  File "/usr/local/lib/python3.6/site-packages/monasca_agent/forwarder/api/monasca_api.py", line 85, in _post
    self._mon_client = self._get_mon_client()                                                                                                                                                             [43/1906]
  File "/usr/local/lib/python3.6/site-packages/monasca_agent/forwarder/api/monasca_api.py", line 141, in _get_mon_client
    session = k.get_session()
  File "/usr/local/lib/python3.6/site-packages/monasca_agent/common/keystone.py", line 339, in get_session
    return self._init_client().session
  File "/usr/local/lib/python3.6/site-packages/monasca_agent/common/keystone.py", line 276, in _init_client
    ks = get_client(**self._config)
  File "/usr/local/lib/python3.6/site-packages/monasca_agent/common/keystone.py", line 191, in get_client
    disc = discover.Discover(session=sess)
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/discover.py", line 178, in __init__
    authenticated=authenticated)
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/_discover.py", line 143, in __init__
    authenticated=authenticated)
  File "/usr/local/lib/python3.6/site-packages/keystoneclient/_discover.py", line 38, in get_version_data
    resp = session.get(url, headers=headers, authenticated=authenticated)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1098, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 747, in request
    auth_headers = self.get_auth_headers(auth)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1158, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/plugin.py", line 95, in get_headers
    token = self.get_token(session)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/identity/base.py", line 88, in get_token
    return self.get_access(session).auth_token
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/identity/base.py", line 134, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/identity/generic/base.py", line 208, in get_auth_ref
    return self._plugin.get_auth_ref(session, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/identity/v3/base.py", line 188, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1106, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 943, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401)
```

Our OpenStack deployment is configured to work with https only and when I `override.yaml` contains:
```
url: http://openstack-control-plane:5000/v3
```

I get:
```
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://spsrc-openstack.iaa.csic.es:5000/v3/auth/tokens: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

Could you please let me know whether I am missing something obvious??

Many thanks,
Sebastian

**Comment by brtkwr** [comment]
Looks like you are using a self signed cert? @dougszumski may know if the agent accepts ca-cert file as an argument in which case this file can be mounted into the container.

**Comment by sebastian-luna-valero** [comment]
Thanks @brtknr 

It is a trusted CA signed certificate, what else could I check?

**Comment by brtkwr** [comment]
Reading the error again, looks like the credentials are wrong based on `keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401)`

**Comment by sebastian-luna-valero** [comment]
True, I had configured the wrong project name and it is now solved. Many thanks for your help and apologies for the noise.
